name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        rails-version: ['5.1.1', '5.2.8', '6.0.6', '6.1.7', '7.0.4']
        exclude:
          - ruby-version: 2.7
            rails-version: 7.0.4
          - ruby-version: 3.0
            rails-version: 5.1.1
          - ruby-version: 3.0
            rails-version: 5.2.8
          - ruby-version: 3.1
            rails-version: 5.1.1
          - ruby-version: 3.1
            rails-version: 5.2.8
          - ruby-version: 3.2
            rails-version: 5.1.1
          - ruby-version: 3.2
            rails-version: 5.2.8
    env:
      ACTIVERECORD: ${{ matrix.rails-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
